### PR TITLE
Allow a testing parameter to be passed of -t 

### PR DESCRIPTION
**Pull request by polevaultweb**
for conditionals in the build config.

### CODE REVIEW

**Comment by polevaultweb** [comment]
@bradt any reason why we can't get this merged, and make https://github.com/deliciousbrains/wp-plugin-build/pull/7 redundant?

**Comment by bradt** [comment]
How does this make #7 redundant?

What exactly would `-t` be used for? For testing the `plugin-build` script itself or creating a build for testing?

**Comment by polevaultweb** [comment]
> How does this make #7 redundant?

Because Gilbert's fix for spaces has already been merged into the `reorganization` branch, ie. no need to merge it into this branch.

We've been using this branch and the testing flag to make sure the plugin build for the free plugins doesn't bother asking about adding to wp.org or github (free) - https://github.com/deliciousbrains/wp-aws/blob/develop/build-cfg/amazon-s3-and-cloudfront/pre-zip.php#L4

This is helpful for the unit test script and doing it locally without worrying about pushing to other places!

**Comment by bradt** [comment]
Ah I see. Hmm, sounds like not publishing should be the default. That is, we could add a publish arg `-p` for when we need to publish to .org and GitHub. Make sense?

**Comment by polevaultweb** [comment]
Yeah that works for me, will work on that

**Comment by A5hleyRich** [comment]
@polevaultweb the reorganisation branch has been merged into master now, so the PR will need opening off of master.

**Pull request closed without merging**
